<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  
  <div></div>

<script>
  // try 和 catch 必须一起使用, 就算发生了错误, js也会继续执行!!!
  // try 表示尝试执行某段代码
  // catch, 只要try中代码发生了错误, 就会执行catch中的代码
  // finally: 不管try中的代码执行是否成功, 都会执行finally的代码
  // try {
  //   var div = document.querySelector('div'); 
  //   div.innerText = '123';
  // }
  // catch(e) {  // exception 异常, 错误
  //   console.error(e);
  //   console.log('div不存在, 执行错误')
  // }
  // finally {
  //   console.log('不管 try 中的代码执行是否报错, 都会执行finally的代码')
  // }

  // console.log(1111);
  // console.log(2222);

  

  // try 尝试执行某段代码, 就算错误, 不会让js停止运行
  // catch 一旦try错误了, 就会执行catch中的代码, 可以在catch中专门的处理错误
  // finally 不管try执行是否报错, 都会执行finally
  
</script>
</body>
</html>